/*Making the database*/
CREATE DATABASE Student;

USE Student;

CREATE TABLE Student(Names VARCHAR(50) PRIMARY KEY, SRN VARCHAR(50) NOT NULL, SUBJECT VARCHAR(50) NOT NULL);

INSERT INTO TABLE (NAMES, SRN, SUBJECT)
VALUES("INGENIOUS", "PES2UG22CS615", "CS");
